name: GitHub Actions
run-name: ${{ github.actor }} is run GitHub Actions 🚀
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install -f
      - name: Run eslint
        run: npm run eslint
      - name: Run stylelint
        run: npm run stylelint
      - name: Run unit testing
        run: npm test
      - name: Building dev application
        run: npm run build:dev
      - name: Building storybook
        run: npm run build-storybook
      - name: Run screenshot testing
        run: npm run loki:ci
